### ISSUE TITLE
Beta banner - whitespace not showing before hyphen

### ISSUE THREAD

**Issue by Fenwick17** [hmrc/frontend-template-provider#15]
There should be space before the hyphen in the beta banner, however this does not show.   
Expected content:   
`This is a new service - your feedback will help us to improve it.`
Actual:  
`This is a new service- your feedback will help us to improve it.`

**Comment by roblav** [comment]
Checking this locally, it looks fine. Can you confirm that this is still an issue? It looks like there was a &nbsp; added on 29th Sept.
![image](https://user-images.githubusercontent.com/660238/33671665-22be83fa-daa0-11e7-8613-4848ea7a1acd.png)

**Comment by Fenwick17** [comment]
Issue seems to be have been resolved.
